// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_SV_yW8x6z9U3DvdKKCFMRDl6QmWI_U',
    appId: '1:709455838949:web:508965ef4e8992c4059e0c',
    messagingSenderId: '709455838949',
    projectId: 'parking-app-3fc91',
    authDomain: 'parking-app-3fc91.firebaseapp.com',
    storageBucket: 'parking-app-3fc91.firebasestorage.app',
    measurementId: 'G-JEW1SLQ38J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWLculdvlf7gwPG6NsVeHw1SYbDKkt1QQ',
    appId: '1:709455838949:android:c402fae58c6926ae059e0c',
    messagingSenderId: '709455838949',
    projectId: 'parking-app-3fc91',
    storageBucket: 'parking-app-3fc91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSYHH-s_eRExxE6g4861Cwnb3ZQ02wEKo',
    appId: '1:709455838949:ios:7f2ca939d3001a41059e0c',
    messagingSenderId: '709455838949',
    projectId: 'parking-app-3fc91',
    storageBucket: 'parking-app-3fc91.firebasestorage.app',
    iosClientId: '709455838949-bu9ufvvsenvrm3p5ous5sq0e5va7lkke.apps.googleusercontent.com',
    iosBundleId: 'com.rnpk.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSYHH-s_eRExxE6g4861Cwnb3ZQ02wEKo',
    appId: '1:709455838949:ios:6ed2ab9eb6574550059e0c',
    messagingSenderId: '709455838949',
    projectId: 'parking-app-3fc91',
    storageBucket: 'parking-app-3fc91.firebasestorage.app',
    iosClientId: '709455838949-pem4gou5l0s19dnqkns0eo6h08v89fir.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV_SV_yW8x6z9U3DvdKKCFMRDl6QmWI_U',
    appId: '1:709455838949:web:8505a398a93416ee059e0c',
    messagingSenderId: '709455838949',
    projectId: 'parking-app-3fc91',
    authDomain: 'parking-app-3fc91.firebaseapp.com',
    storageBucket: 'parking-app-3fc91.firebasestorage.app',
    measurementId: 'G-C9KND0S1FB',
  );

}